TheFenrisLycaon/DSA-C--

Structures/Stack_Using_Queues.cpp
=> Stack using 2 Queues

Algorithms/LongestCommonSubsequence.cpp, DOCS/CONTRIBUTING.md
Longest Common Subsequence
Time complexity: O(n*m)
Dynamic Programming Memoisation
=> LCS issue #3

Algorithms/DepthFirstSearch.cpp
Added Depth First Search Algorithm code written in CPP.
Time complexity: O(V + E), where V is the number of vertices and E is the number of edges in the graph.
Space Complexity: O(V). 
Since an extra visited array is needed of size V.
=> Added Depth First Search Algorithm

Algorithms/BreadthFirstSearch.cpp
Added Breadth First Search Algorithm code written in CPP.
Time complexity: O(V + E), where V is the number of vertices and E is the number of edges in the graph.
Space Complexity: O(V) , since at worst case you need to hold all vertices in the queue.
reference to issue #21
=> Add Breadth First Search Algortithm

Algorithms/KadaneAlgorithm.cpp
Kadane's algorithm for largest sum contiguous subarray
Time Complexity: O(n)
Using DP
Related Issue: #19
=> kadane algorithm added

Algorithms/LongestPalindromicSubstring.cpp
Added C++ code for Longest Palindromic Substring
Time Complexity: O(n^2)
Related Issue: #27
=> Longest palindromic substring added

Algorithms/Tries_Bash.cpp
=> Tries_Bash is added

Java/Algorithms/Sorting Algorithms/Selection_Sort.java
=> Created Solution for Selection Sort Algorithm Using Java issue

Java/Algorithms/Sorting Algorithms/Bubble_Sort.java
=> Created Solution for Bubble Sort Algorithm Using Java issue

Graphs/Dijsktra's Algorithm.cpp, Structures/Tree.cpp
Added Dijsktra's Algorithm in c++
=> Added code

Haskell/Algorithms/InsertionSort.hs
=> Added insertion sort in haskell

GO/Structure/binary-search-tree/main.go
=> Addedd binary search tree in go

C++/Algorithms/BubbleSort.cpp
=> Added Bubble Sort Algorithm in C++

.gitignore, C++/Algorithms/ArraySubsetofanotherarray.cpp
Added an important question based on hash table
Please merge it
=> Question based on hash table

C++/Algorithms/isomorphic_strings.cpp, C++/Algorithms/nqueen.cpp
added isomorphic strings using hashing
=> Adding hashing algos

C++/Algorithms/nqueen.cpp
N Queen Problem using BackTracking
=> N Queen Problem using BackTracking

C++/Algorithms/Key_pair.cpp
A Question for hashing Asked frequently in interviews
=> Added a Good Question

C++/Structures/queue_from_scratch.cpp
Added code to build Queue Data Structure without using arrays, linked list but implementing it with basic operations in queue.
=> Building Queue data structure from scratch in CPP

C++/Algorithms/hashing1.cpp
This is a code to find out the most frequent element of the given array.
=> Code for hashing is being added to find most frequent element of an array

Java/Algorithms/Sorting Algorithms/Quick_Sort.java
This is a code written in java for sorting.
please add a hacktober tag to my pr.
=> Quick_Sort

Java/Algorithms/Sorting Algorithms/MergeSort.java
=> Merge Sort Added

DOCS/inorder_traversal.cpp, DOCS/postorder_traversal.cpp, DOCS/preorder_traversal.cpp
Added Functions to perform Traversals of a Binary Tree.
=> Functions to perform Traversals of a Binary Tree.

C++/Algorithms/InsertionSort.cpp
=> Added Insertion Sort in C++

C++/Structures/queue_using_stacks.cpp
- Added Queue using Stacks in C++ language.
=> Added Queue Using stacks

C/Algorithm/Sparse_Representation.c
This C program first checks if the initial matrix is suitable for Sparse Representation or not and then represents it.
=> Sparse Matrix Representation using C
